name: TierOneCoverage

on: workflow_dispatch

jobs:
  check-coverage:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Make Temp Dir for Artifacts
        run: |
          pwd
          mkdir coverageDir 
          touch coverageDir/coverage.csv

      - name: Run Coverage on Tier One Plugins
        run: |
          pwd
          for plugin in ${{ vars.TIER_ONE_PLUGINS_ICON }}
          do
            echo $plugin >> coverageDir/coverage.csv
          done
          cat coverageDir/coverage.csv


      - name: Upload Coverage
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverageDir
